### PR TITLE
add : new card [emoji-card]

### PR DESCRIPTION
**Pull request by rohitroy-github**
Hey, I have added a new card in the repository called "emoji-card" which generates random emojis and adds it into the card !

Here's the JSON scrrenshot >>> 

image

Here's the card >>> 

image

I have made this contribution in accordance with Hacktoberfest !

### CODE REVIEW

**Comment by akanshSirohi** [comment]
1. This is not a valid card to be added.
2. You have made so many unnecessary changes in other files too.

**Comment by rohitroy-github** [comment]
There is nothing mentioned regarding what's a valid card. So are you referring that I can make only text based cards ?

**Comment by akanshSirohi** [comment]
Yes, also this PR contains extra file edits that don't need to be edited to add your card.

**Comment by rohitroy-github** [comment]
> Yes, also this PR contains extra file edits that don't need to be edited to add your card.

Maybe it's because of the formatted in my vs code. I have strictly followed the guidelines.

**Comment by rohitroy-github** [comment]
Can you give me an idea, about what kind of other cards you are thinking about? Then it will help me make a valid one according to your thinking.

**Comment by akanshSirohi** [comment]
Disable any auto code formatting and add a text based card, you can add the theme also.
Create an issue first for whatever you are adding, I will assign you the task and then you can add new PR.

**Comment by rohitroy-github** [comment]
Yeah cool, I'll do that. But any ideas ?

**Comment by akanshSirohi** [comment]
Its totally upto you.

**Pull request closed without merging**
