### PR TITLE
Picks randomly from every category

### PR DESCRIPTION
**Pull request by sidhant-sriv**
Added a feature that picks a random card from all the categories and displays it as usual.

### CODE REVIEW

**Comment by akanshSirohi** [comment]
@sidhant-sriv I just checked and found out that this is something unique, but there is a drawback of this, if we add new card then that card should also be added in this file `random.js` too, like you have missed motivational quotes card content, I think there might be some other approach that can work, if you could optimize the code further then that should be great.

**Comment by sidhant-sriv** [comment]
Maybe I'll make a separate index that holds the key val names for the types of cards so when a new card is added, only the index needs to be changed and then random.js can just use that index?

**Comment by akanshSirohi** [comment]
@sidhant-sriv Sure that can be done. 
Also it will be great if you can do one more thing that let the card file do its stuff, just fetch the svg or content according to the card default settings..?

**Comment by sidhant-sriv** [comment]
Not sure what you mean but I'll try the index thing in the mean time

**Comment by akanshSirohi** [comment]
@sidhant-sriv Okay, you can also edit the current index file to serve randomly different cards if random-card route is hitted, the we don't need to create new `random-card.js` file. I think that might be a better option.

**Comment by sidhant-sriv** [comment]
> @sidhant-sriv Okay, you can also edit the current index file to serve randomly different cards if random-card route is hitted, the we don't need to create new `random-card.js` file. I think that might be a better option.

So in `index.js` the random route just redirects to one of the current routes?

**Comment by akanshSirohi** [comment]
@sidhant-sriv Exactly, you just need to create the object with keys and values and one exception path that picks from all the values available from that object.

**Comment by sidhant-sriv** [comment]
> @sidhant-sriv Exactly, you just need to create the object with keys and values and one exception path that picks from all the values available from that object.

Alright I'll make the random route to just redirect to the other routes. Lmk what changes to make after that.

**Comment by sidhant-sriv** [comment]
Hopefully this is good enough for a merge :P

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
1. Please remove `random.js` file.
2. And `index.js` file can still be optmized, if someone have to add new card then he would have to make entries in two different places, please use the object approach I gave and use loop for adding middleware.
3. Add new card entry just got merged.
4. Take care of query parameters.

**Comment by sidhant-sriv** [comment]
> 1. Please remove `random.js` file.
> 2. And `index.js` file can still be optmized, if someone have to add new card then he would have to make entries in two different places, please use the object approach I gave and use loop for adding middleware.
> 3. Add new card entry just got merged.
> 4. Take care of query parameters.

removed `random.js`
Optimized `index.js`
added new card entry
I'm not sure what to do about 4.

**Comment by akanshSirohi** [comment]
You still didn't took care of query parameters, of some given, then hey will get ignored by your current approach, fix that and this will get merged.

**Comment by sidhant-sriv** [comment]
> You still didn't took care of query parameters, of some given, then hey will get ignored by your current approach, fix that and this will get merged.

Please tell me how to fix this. I'm not sure what to do.

**Comment by akanshSirohi** [comment]
Okay, I will fix that by myself, check after that done.

**Review by akanshSirohi — APPROVED** [review]

**Comment by akanshSirohi** [comment]
@sidhant-sriv Take pull and now check `index.js`

**Comment by sidhant-sriv** [comment]
Ah, okay like that. Understood. Very nice.
You basically extracted the the URL params and appended it to the redirect url 👍🏽

**Pull request merged**
