### PR TITLE
Travel Destination Cards

### LINKED ISSUE #99: Travel Destination Card
@akanshSirohi This card showcases a popular travel destination and it's related fact. Please Assign this issue to me if you like this idea. 
Thank you

### PR DESCRIPTION
**Pull request by Artemiskgg1**
Added travel destination Card. Resolved all the conflicts.
The JSON file now contains 100 entries.
This PR closes #99

### CODE REVIEW

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
@Artemiskgg1 Please add your card to README.md.

**Comment by Artemiskgg1** [comment]
> @Artemiskgg1 Also you don't need to close the PR to make changes, you can just continue with your changes in the same PR.

okay Will do it right now!

**Comment by Artemiskgg1** [comment]
@Anniebhalla10 Added the card to README.MD

**Comment by akanshSirohi** [comment]
@Artemiskgg1 Your branch merged, you can checkout themes too in the project for contribution. Happy Coding :)

**Pull request merged**
