### PR TITLE
Tech trivia joke cards

### LINKED ISSUE #73: Adding tech trivia cards.
Cards generate a random tech-related fact on every page load, ensuring fresh content.

### PR DESCRIPTION
**Pull request by taneeshaa15**
Hi @akanshSirohi  ,
I hope you're doing well. I've addressed the issue (closes #73)  and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
@taneeshaa15 Please take pull from your branch as I have fixed few things, and add your card to help.js and readme.md so others can see that your card exist.

**Comment by taneeshaa15** [comment]
@akanshSirohi I updated the branch and fixed all the issues now.

**Comment by akanshSirohi** [comment]
@taneeshaa15 Please review how other cards are structured and their outputs. Take the time to carefully verify your card, ensuring everything is correct. Approach this as an opportunity to learn and improve. Make any necessary adjustments to fix your card.

**Comment by akanshSirohi** [comment]
@taneeshaa15 I have fixed the conflicts for you, rest you can take pull from your branch and fix your card.

**Pull request closed without merging**
