### PR TITLE
Created Fun Fact Card 

### PR DESCRIPTION
**Pull request by Sameera-05**
Hey, thank you for reviewing my pull request! 🙌

In this PR, I have added a new card called "Fun Fact Card" to replace the previously created Wordle Card. I’ve followed the existing structure for cards, including adding data for the fun facts, and making necessary adjustments to the readme file as well.

I’ve made the following changes:
- Added the Fun Fact Card with at least 100 entries in the data file.
- Updated README.md to include the Fun Fact Card in the preview section.
- Added the route for the Fun Fact Card to index.js.
- Updated help.js with the necessary API information for the Fun Fact Card.

If there are any issues or mistakes, I would really appreciate your guidance! 🙏 I'm happy to learn and make any necessary corrections.

For clarity, I’m attaching the output from my localhost (running on port 5000) to show that the card is working correctly on my local machine.

Thanks for your time and support!
image
image

### CODE REVIEW

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
@Sameera-05 Please resolve conflicts in your PR

**Comment by Sameera-05** [comment]
Hello

***@***.***,I have already resolved all conflicts. Are there any more?*

**Comment by Sameera-05** [comment]
I resolved all the file conflicts.

**Comment by Sameera-05** [comment]
Hi, I was checking to see if the merge conflicts are resolved and if the merge can go through. Also, could you please change the "Hacktober" label to "hacktoberfest-accepted" so that this PR can be counted for Hacktoberfest? Thanks!

**Comment by akanshSirohi** [comment]
Well I am a working professional and didn't got enough time to review your changes, I will look into them and merge your branch

**Comment by akanshSirohi** [comment]
@Sameera-05 There were still issues in your branch, I have fixed them, but please look for contributions guidelines and check your project is working fine after your conflict fixes from next time. Happy Coding :)

**Pull request merged**
