### PR TITLE
Adding security tips cards

### LINKED ISSUE #82: [idea] Security Tip Card
"Security Tip Card" – Provides daily security tips to help developers write safer code and understand security best practices.

### PR DESCRIPTION
**Pull request by alexwastaken**
added security cards closes #82

### CODE REVIEW

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
@alexwastaken Please read the contribution steps carefully before making PR. Add your card into index.js and README.md. Make atleast 100 entries to your card and remove all conflicts in your branch.

**Comment by alexwastaken** [comment]
> @alexwastaken Please read the contribution steps carefully before making PR. Add your card into index.js and README.md. Make atleast 100 entries to your card and remove all conflicts in your branch.

changes have been applied

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
@alexwastaken Please add your card to Readme.md too

**Comment by alexwastaken** [comment]
@akanshSirohi added

**Pull request merged**
