### PR TITLE
add : new card [word-of-the-day-card]

### LINKED ISSUE #27: thought : can I do word of the day card ?
Sample data : 
{
        "index": 0,
        "word": "abate",
        "meaning": "to become less intense or widespread"
    },
    {
        "index": 1,
        "word": "acerbic",
        "meaning": "sharp and forthright in speech or manner"
    },
    {
        "index": 2,
        "word": "benevolent",
        "meaning": "well-meaning and kindly"
    },
    {
        "index": 3,
        "word": "candor",
        "meaning": "the quality of being open and honest"
    },
    {
        "index": 4,
        "word": "deleterious",
        "meaning": "causing harm or damage"
    },
    {
        "index": 5,
        "word": "ephemeral",
        "meaning": "lasting for a very short time"
    },

### PR DESCRIPTION
**Pull request by rohitroy-github**
I added this new card which generated a random word and shows it's meaning to the user. 
closes #27

### CODE REVIEW

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
Remove extra changes you have done in README.md file in the table of following heading
`List of card names currently available`

**Comment by rohitroy-github** [comment]
This is the changed README portion >>>

image

What exactly do you want me to remove ?

**Comment by akanshSirohi** [comment]
Remove these extra edits, then I will merge your PR
Untitled

**Comment by rohitroy-github** [comment]
@akanshSirohi Check !

**Review by akanshSirohi — APPROVED** [review]

**Comment by akanshSirohi** [comment]
@rohitroy-github Your new card has been added and its live now, you can check here: [https://github-cards.onrender.com](https://github-cards.onrender.com)

**Comment by rohitroy-github** [comment]
Yeah got it.

**Pull request merged**
