### PR TITLE
Refactor code to dynamically generate themes and cards

### LINKED ISSUE #108: [REFACTOR] Dinamically get available cards
I made new PR with update simplify how you handle cards in index.js file. Instead of manually adding each card one by one, the code now imports them dynamically

This was made on PR #107

### PR DESCRIPTION
**Pull request by MaximilianoCabreraP**
I've made some changes to simplify how we handle themes and cards in the project. Instead of manually adding each card one by one, the code now imports them dynamically. This means any new card added to the ./src/cards directory gets picked up automatically—no extra coding required!

Olso i update the README.md.

closes #108

### CODE REVIEW

**Comment by akanshSirohi** [comment]
@MaximilianoCabreraP This is nice update, but it will change the route of every card, you have to rename each file in this PR to keep the route intact.

**Comment by MaximilianoCabreraP** [comment]
It's not necessary; the route runs fine and adapts everything. Here is the URL where I'm running it on my localhost for you to review: https://rna-vegas-closing-senators.trycloudflare.com
image

**Comment by MaximilianoCabreraP** [comment]
i saw the issue, my bad 🙏 
Im working on it

**Comment by akanshSirohi** [comment]
@MaximilianoCabreraP I will close this PR in 24 hours or please make the changes.

**Pull request closed without merging**
