### PR TITLE
New card challenge of the week

### LINKED ISSUE #30: Challenge of the Week Card
Genrates a spontaneous task for you to tackle during the upcoming week.

### PR DESCRIPTION
**Pull request by Anniebhalla10**
closes #30

### CODE REVIEW

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
1. Your card info not added correctly in `README.md` file, fix it.
2. You have changed the port from `5000` to `5001`, undo it.
3. Add more challenges.

**Review by akanshSirohi — APPROVED** [review]

**Comment by akanshSirohi** [comment]
@Anniebhalla10 Add "Challenge of the week" text inside card, so it would look like
```
Challenge of the week
Challenge text
```

**Review by akanshSirohi — CHANGES_REQUESTED** [review]
Add "Challenge of the week" text inside card

**Comment by Anniebhalla10** [comment]
> Add "Challenge of the week" text inside card

Does it now look better?

**Review by akanshSirohi — APPROVED** [review]

**Pull request merged**
