### PR TITLE
new theme added

### LINKED ISSUE #42: New theme
I would like to add a new theme for the cards

### PR DESCRIPTION
**Pull request by kmnat**
new theme added - lemonade
image

closes #42

### CODE REVIEW

**Review by akanshSirohi — APPROVED** [review]
Changes are fine!

**Comment by akanshSirohi** [comment]
@kmnat I have just saw that you have not made changes in README.md, well I will do it by myself.

**Comment by kmnat** [comment]
@akanshSirohi 
I apologise for that

**Comment by akanshSirohi** [comment]
@kmnat Your card is live, you can check now.

**Comment by kmnat** [comment]
Thanks a lot @akanshSirohi

**Pull request merged**
